# Generated by Django 6.1.1 on 2026-09-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rentalagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField()),
                ('billing_from', models.DateField()),
                ('billing_to', models.DateField()),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='generated', max_length=20)),
                ('tenant_name', models.CharField(max_length=200)),
                ('tenant_gst', models.CharField(blank=True, max_length=50)),
                ('tenant_pan', models.CharField(blank=True, max_length=20)),
                ('tenant_mobile', models.CharField(blank=True, max_length=20)),
                ('tenant_email', models.EmailField(blank=True, max_length=254)),
                ('billing_address', models.TextField(blank=True)),
                ('property_name', models.CharField(max_length=200)),
                ('property_address', models.TextField(blank=True)),
                ('unit_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.rentalagreement')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.renter')),
            ],
            options={
                'ordering': ['-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('rent', 'Rent'), ('parking', 'Parking')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('unit_number', models.CharField(blank=True, max_length=50)),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('slots', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('bill_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
