# Generated by Django 6.1.1 on 2026-09-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
