# Generated by Django 6.1.1 on 2026-09-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='owner_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='owner_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='owner_company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='owner_gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='owner_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='owner_pan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='owner_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='owner_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
