# Generated by Django 6.1.1 on 2026-09-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_migrate_renter_to_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalagreement',
            name='renter',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='renter',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_agreements', to='core.property'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_agreements', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_agreements', to='core.unit'),
        ),
        migrations.DeleteModel(
            name='Renter',
        ),
    ]
