# Generated by Django 6.1.1 on 2026-09-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_rentalagreement_renter_remove_invoice_renter_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_property_unit_number',
        ),
        migrations.RemoveField(
            model_name='rentalagreement',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
