# Generated by Django 6.1.1 on 2026-09-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_unit_unique_property_unit_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_slot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='property',
            name='purchased_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='property',
            name='tower',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
