# Generated by Django 6.1.1 on 2026-09-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_property_gst_number_property_parking_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lap_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='LAP Amount'),
        ),
        migrations.AddField(
            model_name='property',
            name='lap_maturity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_installment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='property',
            name='per_sqft_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='property',
            name='stamp_duty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='property',
            name='total_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Unit No'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(verbose_name='Property Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold-out'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Area (sq. ft.)'),
        ),
    ]
