# Generated by Django 6.1.1 on 2026-09-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_property_lap_amount_property_lap_maturity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='gst_delhi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='gst_haryana',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
