# Generated by Django 6.1.1 on 2026-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_owner_gst_delhi_owner_gst_haryana_owner_owner_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='id_number',
            new_name='id_number_1',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='move_in_date',
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_number_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_number_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_type_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_type_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_type_3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
