# Generated by Django 6.1.1 on 2026-09-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_id_number_tenant_id_number_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('increase_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('increase_accepted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_history', to='core.rentalagreement')),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
    ]
