# Generated by Django 6.1.1 on 2026-09-11 16:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_renthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='gstin',
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='increase_frequency_months',
            field=models.PositiveIntegerField(choices=[(6, 'Every 6 Months'), (12, 'Every 1 Year'), (24, 'Every 2 Years')], default=12, help_text='Frequency of rent increase in months.'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='next_increase_date',
            field=models.DateField(blank=True, help_text='Date when the next rent increase becomes due.', null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='rent_increase_pending',
            field=models.BooleanField(default=False, help_text='Whether a rent increase is waiting for approval.'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='rent_increase_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rent increase percentage.', max_digits=5),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
    ]
