# Generated by Django 6.1.1 on 2026-09-12 14:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_owner_company_name_remove_owner_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='term1_increase_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Rent increase percentage for Term 1.', max_digits=5),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='term2_increase_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Rent increase percentage for Term 2.', max_digits=5),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='term3_increase_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Rent increase percentage for Term 3.', max_digits=5),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='term4_increase_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Rent increase percentage for Term 4.', max_digits=5),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='term5_increase_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Rent increase percentage for Term 5.', max_digits=5),
        ),
    ]
