# Generated by Django 6.1.1 on 2026-09-29 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_propertytax'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200, verbose_name='Document Name')),
                ('document', models.FileField(upload_to='property_documents/', verbose_name='Scanned PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.property')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
