# Generated by Django 6.1.1 on 2026-09-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_propertydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
