# Generated by Django 6.1.1 on 2026-10-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_rentalagreement_to_leaseagreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='next_increase_date',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='rent_increase_pending',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='term1_increase_percent',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='term2_increase_percent',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='term3_increase_percent',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='term4_increase_percent',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='term5_increase_percent',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='free_parking_spaces',
            field=models.PositiveIntegerField(default=0, help_text='Number of free parking spaces.'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='lock_in_months',
            field=models.PositiveIntegerField(default=36, help_text='Lock-in period in months.'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='rent_free_months',
            field=models.PositiveIntegerField(default=0, help_text='Number of rent-free months.'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly rent for this lease agreement.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='parking_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly parking charge.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_agreements', to='core.property'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Security deposit for this lease agreement.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_agreements', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='renthistory',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
