# Generated by Django 6.1.1 on 2026-10-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_leaseagreement_next_increase_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_number', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('extension_months', models.PositiveIntegerField(default=36)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='core.leaseagreement')),
            ],
            options={
                'ordering': ['extension_number'],
                'constraints': [models.UniqueConstraint(fields=('lease_agreement', 'extension_number'), name='unique_lease_extension_number')],
            },
        ),
    ]
