# Generated by Django 6.1.1 on 2026-10-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_leaseextension'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaseextension',
            name='unique_lease_extension_number',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='extension_1_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='extension_1_monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='extension_1_security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='extension_1_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='extension_2_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='extension_2_monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='extension_2_security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='extension_2_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LeaseExtension',
        ),
    ]
