# Generated by Django 6.1.1 on 2026-10-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_leaseextension_unique_lease_extension_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='paid_parking_spaces',
            field=models.PositiveIntegerField(default=0, help_text='Number of paid parking spaces.'),
        ),
    ]
