# Generated by Django 6.1.1 on 2026-10-05 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_leaseagreement_paid_parking_spaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_end_date', models.DateField()),
                ('reminder_date', models.DateField()),
                ('reminder_type', models.CharField(choices=[('six_months', 'Six Months Before Expiry'), ('monthly', 'Monthly Renewal Reminder'), ('expiry', 'Lease Expiry')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('in_app_created', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_reminders', to='core.leaseagreement')),
            ],
            options={
                'ordering': ['reminder_date', 'lease_end_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.leaseagreement')),
                ('reminder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='core.renewalreminder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='renewalreminder',
            constraint=models.UniqueConstraint(fields=('lease_agreement', 'lease_end_date', 'reminder_date', 'reminder_type'), name='unique_lease_renewal_reminder'),
        ),
    ]
