# Generated by Django 6.1.1 on 2026-10-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_renewalreminder_leasenotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='rental_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rental Area (sq. ft.)'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='rental_rate_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rental Rate per Sq. Ft.'),
        ),
    ]
