# Generated by Django 6.1.1 on 2026-10-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_leaseagreement_rental_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='rental_rate_per_sqft',
        ),
    ]
