# Generated by Django 6.1.1 on 2026-10-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_leaseagreement_rental_rate_per_sqft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='rent_free_months',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='rent_free_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Example: first 60 days rent-free.', verbose_name='Rent-Free Period (Days)'),
        ),
    ]
