# Generated by Django 6.1.1 on 2026-10-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_leaseagreement_rent_free_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_previous_tax_arrears',
            field=models.BooleanField(default=False, verbose_name='Any Previous Arrears?'),
        ),
        migrations.AddField(
            model_name='property',
            name='municipality_property_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Municipality Property ID'),
        ),
        migrations.AddField(
            model_name='property',
            name='mutation_done',
            field=models.BooleanField(default=False, verbose_name='Mutation Done?'),
        ),
        migrations.AddField(
            model_name='property',
            name='pending_property_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pending Property Tax (₹)'),
        ),
    ]
