# Generated by Django 6.1.1 on 2026-10-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_property_has_previous_tax_arrears_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytax',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('cheque', 'NBT / Cheque NBR'), ('cash', 'Cash')], default='', max_length=20, verbose_name='Paid By'),
        ),
    ]
