# Generated by Django 6.1.1 on 2026-10-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_propertytax_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytax',
            name='noc_received',
            field=models.BooleanField(default=False, verbose_name='NOC Received'),
        ),
    ]
